flowchart TD
%% generated in 0.01s

    %% Entry points (blue)
    classDef entry fill:#4dabf7,stroke:#1971c2,color:#fff

    subgraph Core
        adapters__bash__urirun__urirun_command["urirun_command"]
        adapters__bash__urirun__urirun_document["urirun_document"]
        adapters__perl__Urirun__new["new"]
        adapters__perl__Urirun__command["command"]
        adapters__perl__Urirun__bindings_json["bindings_json"]
        adapters__new_connector__main["main"]
        adapters__rust__src__new["new"]
        adapters__rust__src__target["target"]
        adapters__rust__src__command["command"]
        adapters__rust__src__bindings_json["bindings_json"]
        adapters__rust__examples__hash_connector__main["main"]
        adapters__ts__example__hash_connector__c["c"]
        adapters__ts__urirun__Connector__command["command"]
        adapters__ts__urirun__Connector__toJSON["toJSON"]
        adapters__ts__urirun__Connector__connector["connector"]
        ...["+208 more"]
    end

    subgraph Exporters
    end

    class adapters__bash__urirun__urirun_command,adapters__bash__urirun__urirun_document,adapters__perl__Urirun__new,adapters__perl__Urirun__command,adapters__perl__Urirun__bindings_json,adapters__new_connector__main,adapters__rust__src__new,adapters__rust__src__target,adapters__rust__src__command,adapters__rust__src__bindings_json entry
